# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Hubsite installation tasks
  when: hubsite_enabled | bool
  tags:
    - setup-all
    - setup-hubsite
    - install-all
    - install-hubsite
  block:
    - name: Validate Hubsite configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Hubsite
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Hubsite uninstallation tasks
  when: not hubsite_enabled | bool
  tags:
    - setup-all
    - setup-hubsite
  block:
    - name: Uninstall Hubsite
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
