# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of Hubsite systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ hubsite_identifier }}.service"
  register: hubsite_service_stat

- when: hubsite_service_stat.stat.exists | bool
  block:
    - name: Ensure Hubsite systemd service is stopped
      ansible.builtin.service:
        name: "{{ hubsite_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Hubsite systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ hubsite_identifier }}.service"
        state: absent

    - name: Ensure Hubsite path does not exist
      ansible.builtin.file:
        path: "{{ hubsite_base_path }}"
        state: absent
