# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Hubsite systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ hubsite_identifier }}.service"
  register: hubsite_service_stat

- name: Uninstall Hubsite systemd services and files
  when: hubsite_service_stat.stat.exists | bool
  block:
    - name: Ensure Hubsite systemd service is stopped
      ansible.builtin.service:
        name: "{{ hubsite_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Hubsite systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ hubsite_identifier }}.service"
        state: absent

    - name: Ensure Hubsite container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ hubsite_container_network }}"
        state: absent

    - name: Ensure Hubsite container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ hubsite_container_network }}
      register: network_deletion_result
      changed_when: hubsite_container_network in network_deletion_result.stdout

    - name: Ensure Hubsite path does not exist
      ansible.builtin.file:
        path: "{{ hubsite_base_path }}"
        state: absent
